CREATE TABLE IF NOT EXISTS users (
    user_id SERIAL PRIMARY KEY
    , first_name VARCHAR(50) NOT NULL
    , last_name VARCHAR(50) NOT NULL
    , login VARCHAR(50) NOT NULL UNIQUE
    , password VARCHAR(30) NOT NULL
    , created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);